/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedKtaDashRouteImport } from './routes/_authenticated/kta-dash'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedKtaDashIndexRouteImport } from './routes/_authenticated/kta-dash.index'
import { Route as AuthenticatedKtaDashUsersRouteImport } from './routes/_authenticated/kta-dash.users'
import { Route as AuthenticatedKtaDashOfficesRouteImport } from './routes/_authenticated/kta-dash.offices'
import { Route as AuthenticatedKtaDashJobsRouteImport } from './routes/_authenticated/kta-dash.jobs'
import { Route as AuthenticatedKtaDashDepartmentsRouteImport } from './routes/_authenticated/kta-dash.departments'
import { Route as AuthenticatedKtaDashApplicationsIndexRouteImport } from './routes/_authenticated/kta-dash.applications.index'
import { Route as AuthenticatedKtaDashApplicationsAppIdRouteImport } from './routes/_authenticated/kta-dash.applications.$appId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKtaDashRoute = AuthenticatedKtaDashRouteImport.update({
  id: '/kta-dash',
  path: '/kta-dash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKtaDashIndexRoute =
  AuthenticatedKtaDashIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashUsersRoute =
  AuthenticatedKtaDashUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashOfficesRoute =
  AuthenticatedKtaDashOfficesRouteImport.update({
    id: '/offices',
    path: '/offices',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashJobsRoute =
  AuthenticatedKtaDashJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashDepartmentsRoute =
  AuthenticatedKtaDashDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashApplicationsIndexRoute =
  AuthenticatedKtaDashApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)
const AuthenticatedKtaDashApplicationsAppIdRoute =
  AuthenticatedKtaDashApplicationsAppIdRouteImport.update({
    id: '/applications/$appId',
    path: '/applications/$appId',
    getParentRoute: () => AuthenticatedKtaDashRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kta-dash': typeof AuthenticatedKtaDashRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/kta-dash/departments': typeof AuthenticatedKtaDashDepartmentsRoute
  '/kta-dash/jobs': typeof AuthenticatedKtaDashJobsRoute
  '/kta-dash/offices': typeof AuthenticatedKtaDashOfficesRoute
  '/kta-dash/users': typeof AuthenticatedKtaDashUsersRoute
  '/kta-dash/': typeof AuthenticatedKtaDashIndexRoute
  '/kta-dash/applications/$appId': typeof AuthenticatedKtaDashApplicationsAppIdRoute
  '/kta-dash/applications/': typeof AuthenticatedKtaDashApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs': typeof JobsIndexRoute
  '/kta-dash/departments': typeof AuthenticatedKtaDashDepartmentsRoute
  '/kta-dash/jobs': typeof AuthenticatedKtaDashJobsRoute
  '/kta-dash/offices': typeof AuthenticatedKtaDashOfficesRoute
  '/kta-dash/users': typeof AuthenticatedKtaDashUsersRoute
  '/kta-dash': typeof AuthenticatedKtaDashIndexRoute
  '/kta-dash/applications/$appId': typeof AuthenticatedKtaDashApplicationsAppIdRoute
  '/kta-dash/applications': typeof AuthenticatedKtaDashApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kta-dash': typeof AuthenticatedKtaDashRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/kta-dash/departments': typeof AuthenticatedKtaDashDepartmentsRoute
  '/_authenticated/kta-dash/jobs': typeof AuthenticatedKtaDashJobsRoute
  '/_authenticated/kta-dash/offices': typeof AuthenticatedKtaDashOfficesRoute
  '/_authenticated/kta-dash/users': typeof AuthenticatedKtaDashUsersRoute
  '/_authenticated/kta-dash/': typeof AuthenticatedKtaDashIndexRoute
  '/_authenticated/kta-dash/applications/$appId': typeof AuthenticatedKtaDashApplicationsAppIdRoute
  '/_authenticated/kta-dash/applications/': typeof AuthenticatedKtaDashApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/kta-dash'
    | '/profile'
    | '/apply/$jobId'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/kta-dash/departments'
    | '/kta-dash/jobs'
    | '/kta-dash/offices'
    | '/kta-dash/users'
    | '/kta-dash/'
    | '/kta-dash/applications/$appId'
    | '/kta-dash/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/profile'
    | '/apply/$jobId'
    | '/jobs/$jobId'
    | '/jobs'
    | '/kta-dash/departments'
    | '/kta-dash/jobs'
    | '/kta-dash/offices'
    | '/kta-dash/users'
    | '/kta-dash'
    | '/kta-dash/applications/$appId'
    | '/kta-dash/applications'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/kta-dash'
    | '/_authenticated/profile'
    | '/apply/$jobId'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/_authenticated/kta-dash/departments'
    | '/_authenticated/kta-dash/jobs'
    | '/_authenticated/kta-dash/offices'
    | '/_authenticated/kta-dash/users'
    | '/_authenticated/kta-dash/'
    | '/_authenticated/kta-dash/applications/$appId'
    | '/_authenticated/kta-dash/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kta-dash': {
      id: '/_authenticated/kta-dash'
      path: '/kta-dash'
      fullPath: '/kta-dash'
      preLoaderRoute: typeof AuthenticatedKtaDashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kta-dash/': {
      id: '/_authenticated/kta-dash/'
      path: '/'
      fullPath: '/kta-dash/'
      preLoaderRoute: typeof AuthenticatedKtaDashIndexRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/users': {
      id: '/_authenticated/kta-dash/users'
      path: '/users'
      fullPath: '/kta-dash/users'
      preLoaderRoute: typeof AuthenticatedKtaDashUsersRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/offices': {
      id: '/_authenticated/kta-dash/offices'
      path: '/offices'
      fullPath: '/kta-dash/offices'
      preLoaderRoute: typeof AuthenticatedKtaDashOfficesRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/jobs': {
      id: '/_authenticated/kta-dash/jobs'
      path: '/jobs'
      fullPath: '/kta-dash/jobs'
      preLoaderRoute: typeof AuthenticatedKtaDashJobsRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/departments': {
      id: '/_authenticated/kta-dash/departments'
      path: '/departments'
      fullPath: '/kta-dash/departments'
      preLoaderRoute: typeof AuthenticatedKtaDashDepartmentsRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/applications/': {
      id: '/_authenticated/kta-dash/applications/'
      path: '/applications'
      fullPath: '/kta-dash/applications/'
      preLoaderRoute: typeof AuthenticatedKtaDashApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
    '/_authenticated/kta-dash/applications/$appId': {
      id: '/_authenticated/kta-dash/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/kta-dash/applications/$appId'
      preLoaderRoute: typeof AuthenticatedKtaDashApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedKtaDashRoute
    }
  }
}

interface AuthenticatedKtaDashRouteChildren {
  AuthenticatedKtaDashDepartmentsRoute: typeof AuthenticatedKtaDashDepartmentsRoute
  AuthenticatedKtaDashJobsRoute: typeof AuthenticatedKtaDashJobsRoute
  AuthenticatedKtaDashOfficesRoute: typeof AuthenticatedKtaDashOfficesRoute
  AuthenticatedKtaDashUsersRoute: typeof AuthenticatedKtaDashUsersRoute
  AuthenticatedKtaDashIndexRoute: typeof AuthenticatedKtaDashIndexRoute
  AuthenticatedKtaDashApplicationsAppIdRoute: typeof AuthenticatedKtaDashApplicationsAppIdRoute
  AuthenticatedKtaDashApplicationsIndexRoute: typeof AuthenticatedKtaDashApplicationsIndexRoute
}

const AuthenticatedKtaDashRouteChildren: AuthenticatedKtaDashRouteChildren = {
  AuthenticatedKtaDashDepartmentsRoute: AuthenticatedKtaDashDepartmentsRoute,
  AuthenticatedKtaDashJobsRoute: AuthenticatedKtaDashJobsRoute,
  AuthenticatedKtaDashOfficesRoute: AuthenticatedKtaDashOfficesRoute,
  AuthenticatedKtaDashUsersRoute: AuthenticatedKtaDashUsersRoute,
  AuthenticatedKtaDashIndexRoute: AuthenticatedKtaDashIndexRoute,
  AuthenticatedKtaDashApplicationsAppIdRoute:
    AuthenticatedKtaDashApplicationsAppIdRoute,
  AuthenticatedKtaDashApplicationsIndexRoute:
    AuthenticatedKtaDashApplicationsIndexRoute,
}

const AuthenticatedKtaDashRouteWithChildren =
  AuthenticatedKtaDashRoute._addFileChildren(AuthenticatedKtaDashRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKtaDashRoute: typeof AuthenticatedKtaDashRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKtaDashRoute: AuthenticatedKtaDashRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
